export const GET_USERS_LIST = 'GET_USERS_LIST'
export const GET_USERS_LIST_LOADING = 'GET_USERS_LIST_LOADING';
export const GET_USERS_LIST_ASYNC = 'GET_USERS_LIST_ASYNC';
export const GET_USERS_LIST_ERROR = 'GET_USERS_LIST_ERROR';

export const GET_USER_DETAIL_ASYNC = 'GET_USER_DETAIL_ASYNC';
export const GET_USER_DETAIL = 'GET_USER_DETAIL';